### ISSUE TITLE
Farming Station GUI Rendering Wrong (SMP)

### ISSUE THREAD

**Issue by jburrows82** [HenryLoenwind/EnderIO#49]
EIO: 2.3.0.420beta
Core: 0.2.0.31beta
Forge: *.1558

Using Fastcraft 1.22-ctest17, and no Optifine

![image](https://cloud.githubusercontent.com/assets/8468011/11293615/7eec1bc0-8f29-11e5-8450-b67f3c155a59.png)

**Comment by HenryLoenwind** [comment]
Your resource pack is outdated.

You can manually remove the file "resources/assets/enderio/textures/gui/farmStation.png" from the resource pack zip to get a correct display.

Some other GUIs might look a bit funny because of the doubled background icons, but I thing the farming station was the only one with layout changes.

**Comment by jburrows82** [comment]
Figures. Thank you!
